<?php

/*
 * @moduleContract
 * @purpose Exception hierarchy for all ClassBuilder errors: every exception carries a BuildStack for detailed error context.
 * @scope Exception definitions, base class, interface, and all leaf exceptions (14 concrete classes).
 * @input BuildStack instance and optional additional context (e.g., invalid value).
 * @output Descriptive exception message generated by AbstractBuildException from BuildStack + getCause().
 * @links USES_API(10): BuildStack, RuntimeException
 * @links_to_spec All build errors produce BuildExceptionInterface exceptions with full stack trace path
 * @invariants
 * - Every concrete exception extends AbstractBuildException.
 * - AbstractBuildException implements BuildExceptionInterface.
 * - getCause() returns a non-empty string describing the specific reason for failure.
 * @rationale
 * Q: Why a deep exception hierarchy instead of a single exception with error codes?
 * A: Each exception type is catchable by type, enabling precise error handling in client code.
 * Q: Why embed BuildStack in every exception?
 * A: The stack provides the full construction path (e.g., "root->items[0]->name"), essential for debugging.
 * @changes
 * LAST_CHANGE: v1.0.0 – Initial semantic markup of namespace contract
 * @modulemap
 * INTERFACE 10[Contract for all build exceptions] => BuildExceptionInterface
 * CLASS 10[Abstract base for all build exceptions] => AbstractBuildException
 * CLASS 6[Thrown when no build strategy matches the type] => BuildTypeNotFoundException
 * CLASS 6[Thrown when an enum cannot be constructed from given data] => CannotBuildEnumException
 * CLASS 7[Thrown when no type in a union/intersection can build the value] => CannotBuildException
 * CLASS 6[Thrown when CanBeBuiltFromScalar fails due to parameter count] => CannotBuildFromPrimitive
 * CLASS 5[Thrown when a circular reference is detected] => CannotBuildReferenceException
 * CLASS 6[Thrown when a requested class is not found] => ClassNotFoundException
 * CLASS 6[Thrown when an enum type is not found] => EnumNotFoundException
 * CLASS 6[Thrown when AvailableInheritors is missing on abstract/interface] => InheritorsNotSetException
 * CLASS 6[Thrown when an inheritor is not a subclass of the parent] => InheritorsRecursionException
 * CLASS 6[Thrown when a BackedEnum::from() fails for the given value] => InvalidBackedEnumCaseException
 * CLASS 6[Thrown when an inheritor references the parent class itself] => InvalidInheritorsException
 * CLASS 6[Thrown when a UnitEnum case value is not found] => InvalidUnitEnumCaseException
 * CLASS 7[Thrown when a required constructor parameter value is missing] => ValueNotFoundException
 * CLASS 6[Fallback exception for non-BuildExceptionInterface errors] => UnknownException
 * @usecases
 * - [BuildExceptionInterface]: Client → Catch in build()/buildArray() → Handle specific error types
 * - [AbstractBuildException]: ClassBuilder → Throw on build failure → Provide detailed message with BuildStack path
 * - [CannotBuildException]: ClassBuilder → No type in union can build → Rethrow as final error
 * - [InheritorsNotSetException]: CheckClass → Abstract class without inheritors → Signal configuration error
 * - [ValueNotFoundException]: buildObject → Missing required parameter → Report missing data field
 */
